name: Deploy to Firebase
'on':
  push:
    branches:
      - master
jobs:
  firebase-deploy:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@master
        with:
          node-version: '15.x'
      - run: npm install -g @angular/cli
      - run: npm install -g firebase-tools
      - run: npm install
      - run: cd functions && npm install && cd ..
      - run: npm run build:all
      - run: firebase deploy --token ${{secrets.FIREBASE_TOKEN}}

#name: Deploy to Firebase
#'on':
#  push:
#    branches:
#      - master
#jobs:
#  build_and_deploy:
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v2
#      - run: npm insta
#      - run: 'npm run build:all'
#      - uses: FirebaseExtended/action-hosting-deploy@v0
#        with:
#          repoToken: '${{ secrets.GITHUB_TOKEN }}'
#          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_ERNST_PORTFOLIO_PROD }}'
#          channelId: live
#          projectId: ernst-portfolio-prod
#        env:
#          FIREBASE_CLI_PREVIEWS: hostingchannels
